bash /mnt/sfs_turbo/gyx/PPT/scripts_huawei/prompt/cmnli/finetune_t5_cmnli_few_shot_init_vocab.sh 0.005 1 10 64
bash /mnt/sfs_turbo/gyx/PPT/scripts_huawei/prompt/cmnli/finetune_t5_cmnli_few_shot_init_vocab.sh 0.005 1 20 64
bash /mnt/sfs_turbo/gyx/PPT/scripts_huawei/prompt/cmnli/finetune_t5_cmnli_few_shot_init_vocab.sh 0.005 1 30 64
bash /mnt/sfs_turbo/gyx/PPT/scripts_huawei/prompt/cmnli/finetune_t5_cmnli_few_shot_init_vocab.sh 0.005 1 40 64
bash /mnt/sfs_turbo/gyx/PPT/scripts_huawei/prompt/cmnli/finetune_t5_cmnli_few_shot_init_vocab.sh 0.005 1 50 64
bash /mnt/sfs_turbo/gyx/PPT/scripts_huawei/prompt/c3/finetune_t5_c3_few_shot_init_vocab.sh 0.01 1 10 64
bash /mnt/sfs_turbo/gyx/PPT/scripts_huawei/prompt/c3/finetune_t5_c3_few_shot_init_vocab.sh 0.01 1 20 64
bash /mnt/sfs_turbo/gyx/PPT/scripts_huawei/prompt/c3/finetune_t5_c3_few_shot_init_vocab.sh 0.01 1 30 64
bash /mnt/sfs_turbo/gyx/PPT/scripts_huawei/prompt/c3/finetune_t5_c3_few_shot_init_vocab.sh 0.01 1 40 64
bash /mnt/sfs_turbo/gyx/PPT/scripts_huawei/prompt/c3/finetune_t5_c3_few_shot_init_vocab.sh 0.01 1 50 64